config = {
    "bot_description": "Fossil ID - A SciOly Discord Bot for aspiring paleontologists",
    "bot_signature": "Fossil ID - A Paleontology Bot",
    "prefixes": ["f!", "f.", "F!", "F."],
    "id_type": "fossils",
    "github_image_repo_url": "https://github.com/tctree333/Fossil-Bot-Images.git",
    "support_server": "https://discord.gg/2HbshwGjnm",
    "source_link": "https://github.com/tctree333/Fossil-ID",
    "name": "fossil-id",
    "category_name": "Taxon",
    "client_id": 678437690848313373,
    "base_image_url": "https://raw.githubusercontent.com/tctree333/Fossil-Bot-Images/master/",
    "validation_repo_url": "https://github.com/person-v132/SciOlyID-Images.git",
    "validation_repo_dir": "fossil-id",
    "logs": True,
    "bot_files_dir": "bot_files",
    "invite": "https://discord.com/api/oauth2/authorize?client_id=678437690848313373&permissions=51200&scope=bot",
    "authors": "person_v1.32, EraserBird, and hmmm",
    "sentry": True,
    "local_redis": False,
    "backups_channel": 678435444219969538,
    "id_groups": True,
}
